### ISSUE TITLE
Remove old Eventbrite embeds

### ISSUE THREAD

**Issue by gusaus** [OpenProducer/angelcityjazz#68]
Per Rocco in https://github.com/OpenProducer/angelcityjazz/issues/67#issuecomment-2208752313

### Problem
There is an issue with the eventbrite embeds:

- I tried editing the current blocks but they revert to the old link
whenever saving
- I therefore erased the old blocks and inserted new blocks with the
updated ticketing link
- randomly the old block reappears below my new block thus creating
multiple eventbrite buttons. The one that reappears is usually locked and I
have to unlock it and delete but then it reappears.
- I have now erased dozens of these blocks but they keep popping up. The
latest to pop up is on this page:
https://acjstg.wpengine.com/event/mauricioandjeffatbgt/ (note the register
button under the tickets button). I already erased this at least 3 times but
it keeps reappearing.

### Solution 
Remove old embeds from the following events - 

- [x] https://acjstg.wpengine.com/event/krisandsteveatredcat/
- [x] https://acjstg.wpengine.com/event/elsa-nilssons-pulses-sasha-berliner/ (<-- some of the copy for Sasha Berliner's bio seems a bit off - do you have a link to the source?)
- [x] https://acjstg.wpengine.com/event/mauricioandjeffatbgt/
- [x] https://acjstg.wpengine.com/event/joyandderonat2220/
- [x] https://acjstg.wpengine.com/event/foursolosets/
- [x] https://acjstg.wpengine.com/event/jennyandiseulat2220/
- [x] https://acjstg.wpengine.com/event/fes/
- [x] https://acjstg.wpengine.com/event/angelangelcityvernacular/
- [x] https://acjstg.wpengine.com/event/douye-yafeu-tyhinba/

**Comment by gusaus** [comment]
Logging Rocco's additional feedback rom https://github.com/OpenProducer/angelcityjazz/issues/67#issuecomment-2210741362

FYI, it seems to be happening whenever I edit an event page. As soon as the
editing format is loaded, the new eventbrite register button appears,
locked and with last year's event embedded. I think I have removed over 25
of these unwanted blocks.

**Comment by gusaus** [comment]
> The latest to pop up is on this page:
https://acjstg.wpengine.com/event/mauricioandjeffatbgt/ (note the register button under the tickets button). I already erased this at least 3 times but it keeps reappearing.

@angelcityjazz Are you still seeing the register button on https://acjstg.wpengine.com/event/mauricioandjeffatbgt/? (if so, try clearing the cache). I 'think' I was able to remove that without issue and it seems to have saved (I'm checking on multiple browsers and devices).

**Comment by gusaus** [comment]
Rocco - I've now gone through every event and 'deleted' old eventbrite embeds I came across (logged them in the description https://github.com/OpenProducer/angelcityjazz/issues/68#issue-2392922502); I then went back and checked the html in each, just to make sure...

Looks like I was able to remove everything without issue - if you're still seeing extra embeds on your end, try clearing the cache on whatever your browser you're on. 


Really not sure why you were having problems on your end, but I'm sorry I wasn't able to troubleshoot sooner.

**Comment by gusaus** [comment]
I noticed (and deleted) the old eventbrite embed on https://acjstg.wpengine.com/event/douye-yafeu-tyhinba/ when I edited to remove an extra space from the title.

**Comment by angelcityjazz** [comment]
I would place the festival branding text to the top right (under the Donate
button). I think it would look better on a browser. Not sure how that would
work on the Mobile format.

**Comment by angelcityjazz** [comment]
I've been going through the event pages on the live site. Some issues I
found:

- the register buttons are appearing again. I had to remove them manually
by unloaking the embed. Why is this happening? Super annoying
- I had to adjust the focus point on the bio photos as the focus I placed
on the staging site did not carry through to the live site.
- as for the branding, what about placing it to the left of the photo
vertically (text rotated 90 degrees)?

**Comment by gusaus** [comment]
Pretty sure this is the cache issue on your end because I was able to
easily remove the embeds and they haven’t reappeared at least when checking
on my end. Instead of trying to fix yourself, could you just provide a link
to the event pages where you’re having an issue not on the staging site
we’re just focusing on the live site

Also keep logging any other issues and suggestions and I’ll work through
everything once I start my day and a couple of hours



Gus Austin
https://openproducer.org/
https://twitter.com/_openproducer
https://twitter.com/gusaus

**Comment by gusaus** [comment]
I believe this issue has been resolved. Will re-open if it mysteriously pops up again.
