### ISSUE TITLE
Unable to access site

### ISSUE THREAD

**Issue by gusaus** [OpenProducer/angelcityjazz#69]
Below are comments from Rocco about issues he's been having accessing the site.

https://github.com/OpenProducer/angelcityjazz/issues/67#issuecomment-2225004206

> Hi Gus, the server appears to be down. I'm connected to the internet and
> surfing all sort of sites but when I try to load angelcityjazz.com , I get
> this message.
> 
> Offline
> 
> There has been a problem connecting with the server. Please check your
> internet connection or try again later.
>

https://github.com/OpenProducer/angelcityjazz/issues/67#issuecomment-2225031408
> I tried accessing events for 30 minutes with no luck and I was getting a bit
anxious. 

https://github.com/OpenProducer/angelcityjazz/issues/67#issuecomment-2225034570
> Now the events load but when I click on edit I get the offline message again. I checked my connection and it's good so it must be a problem with the server.

https://github.com/OpenProducer/angelcityjazz/issues/67#issuecomment-2226079769
> Seems to be working now. I was not able to make any updates for the past 6
hours. I had no other connectivity issues with any other site.

**Comment by gusaus** [comment]
Referencing this comment below https://github.com/OpenProducer/angelcityjazz/issues/67#issuecomment-2225022579

> Hey Rocco - saw your email come in right before going to bed. Just checked on my phone and laptop - seeing no problems. Also have been monitering and doing performance tests quite frequently ever since the announcement went out.

**Comment by gusaus** [comment]
Hey Rocco - I parsed the hosting related comments into this issue so we can focus on getting to the bottom of why this happened and preventing from happening in the future.

Can you provide addition detail about your setup (device, os, browsers, etc.) and location? We're you experiencing the same issues across multiple devices and browsers?

Just to be clear, you've been accessing the web just fine - this is the only site that's been problematic?

As mentioned in the previous comment, I'm going to point this issue to Tony and see if he ideas about the cause and solution.

**Comment by angelcityjazz** [comment]
Hi Gus, I was using my PC with Chrome connected to a wifi hotspot in Italy.
I was able to load eventbrite and update my events there with no issues. I
was also able to use all of my social media, youtube and any other site I
tried but when accessing angelcityjazz.com some events would give me the
offline message and even if I could load the event, when trying to edit it
would again display the offline message. I tried clearing the cache,
restarting the computer and reconnecting several times but for about 6
hours I was locked out of editing any event.
Quite a few artists are sending me updates and revisions for their event
info so I need to be able to edit the event pages regularly.

Thanks

Rocco

**Comment by gusaus** [comment]
Thanks for providing additional detail. I'm no network/server expert but I've reached out to @tonyzeoli who has a lot of expertise with these issues (WP Engine as a host). I'll also reach out to WP Engine if the problem persists. 

Again, everything is working fine in my location (Seattle) and no issues are coming up in performance tests.

I'll continue to monitor and can also make any changes on your behalf if needed. Just keep me posted (as will I update you).

**Comment by gusaus** [comment]
Hey Rocco - I went ahead and contacted WP Engine support - below is a log of our chat; if you experience similar issues, it will help if you provide info like the IP address and screenshot with the "inspect" section open.....

(11:48:11) | Loki N
Hi Gus! Thanks for contacting WP Engine chat support. How can I help you today?
-- | --
(11:50:01) | Gus Austin
My client, who is currently in Italy, has been having trouble (periodically) accessing his site. He's been able to access and connect with other sites, but for some reason he's having issues connecting to this WP Engine hosted site.

(11:51:03) | Gus Austin
This is the last message he sent me:I was using my PC with Chrome connected to a wifi hotspot in Italy.I was able to load eventbrite and update my events there with no issues. Iwas also able to use all of my social media, youtube and any other site Itried but when accessing angelcityjazz.com some events would give me theoffline message and even if I could load the event, when trying to edit itwould again display the offline message. I tried clearing the cache,restarting the computer and reconnecting several times but for about 6hours I was locked out of editing any event.

(11:52:32) | Loki N
did they send any screenshot by a chance?

(11:52:49) | Gus Austin
no

he did say he got the following message -OfflineThere has been a problem connecting with the server. Please check your internet connection or try again later.

(12:08:28) | Loki N 
I checked few VPN's to access the site from "Italy" and I did not get nay error not on the desktop nor on the mobile. logs are not showing much as well. do you happen to know their IP that was getting an error? or it was few different once as they were moving between hot spots?

(12:11:35) | Gus Austin
I do not know their IP address at the time; nor do I know if they were experiencing similar issues from different hot spots.Assuming you'd need to know that to troubleshoot further?

(12:14:41) | Loki N
sadly, yes. the error they seen suggest more so issue on their end. If there would be a code like 502, 504, 403 ect. I could find their IP by that but since the 'Offline' will not show in my logs it would be like looking for a needle in the haystack

(12:17:04) | Gus Austin
i do know they've had issues making and saving edits; i haven't been able to replicate issues from my location; the performance could be improved (due to file sizes, etc.) but I haven't had issues accessing or editing the site

I'll ask them to provide the IP address but probably won't get a response until tomorrow; anything else I should ask for?

(12:19:36) | Loki N
if they can ask them to take a screenshot with the "inspect" section open

(12:29:59) | Gus Austin
actually one last question; does this sound like a location/connectivity issue on the clients end? or might it be a website performance issue?

(12:32:40) | Loki N
I don’t see any location blocks set up on the site and the site is working from Italy as my test via VPN confirm. It might be the connection local issue for that one person. to make sure maybe ask the cx which pages giving them issues and exact steps to recreate the issue on the back end

**Comment by gusaus** [comment]
Hey Rocco - just checking to see if you've been having any of the same issues accessing and editing the site. 

Based on my chat with support, it seems like (while annoying) the issues you've been having are location based and isolated to you. Still want to make sure, so if you provide the provide info like the IP address and screenshot with the "inspect" section open (as noted in the previous comment) if/when experiencing similar issues I can follow up with support again and try to remedy.

Site still looking/performing nicely on my end, and still planning to work other improvements we've been identifying in https://github.com/OpenProducer/angelcityjazz/issues/67

**Comment by angelcityjazz** [comment]
All working well now. Is there an easy way to have all of the youtube
embeds be the same size?
It looks a bit awkward when they're not:
https://angelcityjazz.com/event/jennyandiseulat2220/

**Comment by gusaus** [comment]
> All working well now.

From the same location/setup? 

Again, it definitely seemed like the problems were isolated to your location and setup, but please log details (skim through https://github.com/OpenProducer/angelcityjazz/issues/69#issuecomment-2226596197) about any issues you come across and I'll respond/remedy when I can.

**Comment by angelcityjazz** [comment]
I'm in a different location but same set-up.
Bty, I noticed a problem with the past festival grid display:
https://angelcityjazz.com/angel-city-jazz-fest/2023-acjf/

The last two events displayed are from this year. I tried adding a display
count limit on the block code but it didn't help.

**Comment by gusaus** [comment]
>
>  I tried adding a display
> count limit on the block code but it didn't help.
>

Actually almost worked but I noticed the 'e' was missing from the
'events_per_page' filter. Looks like it's working now!

**Comment by angelcityjazz** [comment]
Hi Gus, I just ran into another editing issue:

- when trying to edit any event page the blocks with the date, time, venue
and so forth are all displaying this text:
Your site doesn’t include support for the "tribe/event-venue" block. You
can leave this block intact or remove it entirely.

I really need to edit some info on some of the events. What should I do?
Specifically, I need to update the venue on the 10/17 event from Barnsdall
Gallery Theatre to Artshare LA. This needs to happen today!

Thanks

**Comment by angelcityjazz** [comment]
Since I really needed to update this asap, I changed the Barnsdall Venue
info to mirror Artshare LA so that the event now displays the correct info.
I need to be able to edit these details anytime on the fly. Please advise
on how to fix this asap!

thanks

**Comment by gusaus** [comment]
Hey Rocco, were you able to edit what you needed? You should be able to
edit everything even when you see that message.

That said I’ll make sure everything is working and the message doesn’t
display when i’m on the computer in a few hours

**Comment by angelcityjazz** [comment]
I was not able to access those blocks at all. As the message says I can
only leave it as is or delete the block.
My workaround was to change the venue info for the Barnsdall to reflect
Artshare LA. It's just a temporary fix. I need access to the blocks.

**Comment by gusaus** [comment]
You should still be able to swap out the venue. I did notice the license to
the pro plug-in was expired. maybe that has something to do with it? i’ll
have a better idea when I take a look in a an hour or so

**Comment by gusaus** [comment]
Rocco - I'm trying to replicate the issue on https://angelcityjazz.com/wp-admin/post.php?post=19318&action=edit and not only it looks like I'm able to change the venue without issue. 

> Your site doesn’t include support for the "tribe/event-venue" block.

Also not seeing this or other related messages. 

So it seems like this could be another localized issue but you obviously need to be able to edit on the fly without issue.  

That said, can you add or email a screengrab of what you're seeing? Also, have you tried clearing your browser cache?

**Comment by gusaus** [comment]
So when you click on the venue block you "don't" see the option of removing the venue (see the screengrab below)?

<img width="1038" alt="Edit Event “Mauricio Morales + Jeff Denson   Romain Pilon Trio featuring Clarence Penn” ‹ Angel City Jazz — WordPress 2024-07-22 12-38-56" src="https://github.com/user-attachments/assets/d26a89b9-d290-45b1-b20f-eade752ec076">

...looks like you're trying to edit the live site now, so I exited....

**Comment by angelcityjazz** [comment]
Here is a screenshot. It's the same for all events which means I cannot
edit any events

**Comment by gusaus** [comment]
I'm not seeing the screenshot(s) in the GitHub comments - can you email?

**Comment by angelcityjazz** [comment]
No I can’t edit anything. I can inly remove the block

**Comment by gusaus** [comment]
Looking at the screenshot - not sure why you're all of a sudden having this issue (again I'm not able to replicate). Can you try the following on your PC?

> To clear the cache on a PC using Chrome, you can use the following shortcut:
> 
> Open Chrome.
> Clear Cache:
> Press Ctrl + Shift + Delete to open the Clear browsing data window.
> Ensure that Cached images and files is checked.
> Click Clear data.
> 

If that doesn't help, I'll contact WP Engine support again.

**Comment by angelcityjazz** [comment]
I emailed it to you on a separate thread
