### ISSUE TITLE
Unsupported block issue

### ISSUE THREAD

**Issue by gusaus** [OpenProducer/angelcityjazz#70]
Creating a new issue to troubleshoot/resolve the unsupported block issue Rocco described below (also see the screengrab):
![Screenshot 2024-07-22 095117](https://github.com/user-attachments/assets/506b1e88-7d87-470c-93cb-b01eeed7f2fa)

> Hi Gus, I just ran into another editing issue:
> 
> - when trying to edit any event page the blocks with the date, time, venue
> and so forth are all displaying this text:
> Your site doesn’t include support for the "tribe/event-venue" block. You
> can leave this block intact or remove it entirely.
> 
> I really need to edit some info on some of the events. What should I do?
> Specifically, I need to update the venue on the 10/17 event from Barnsdall
> Gallery Theatre to Artshare LA. This needs to happen today!

**Comment by gusaus** [comment]
Hey Rocco - 

Can you login and try to edit the same event on https://acjdev.wpengine.com/ - and send a screengrab of what you see?

If you're still unable to edit, I'm thinking it might have to do with the paid plugin not being renewed.

It's definitely associated with the Events Calandar plugin (and not related to issues w/ other blocks we've resolved).

I'm looking into this further and will post my findings here.

**Comment by gusaus** [comment]
Sorry for bouncing around issues but I wanted to isolate in this issue. Not sure if the screengrab you emailed was on dev - can you just try to edit on https://acjdev.wpengine.com/ and let me know if you're still experiencing the same issue.

Looks like this is a known issue (see https://wordpress.org/support/topic/tribe-blocks-not-working-cant-create-new-event/) and potentially something they fixed with the latest update.

**Comment by gusaus** [comment]
Rocco - I updated the Events Calendar plugin on production (after testing on dev). Also cleared the cache.

Let me know if that resolves the problem.

If not, I'll followup with Events Calendar support (I forget if I have an account or I just email on behalf of you) and it looks like the issue is with them.

**Comment by angelcityjazz** [comment]
That resolved the problem. I can now edit the events normally.

Thank you

Rocco

**Comment by gusaus** [comment]
So glad it was something so simple (and not related to the paid plugin).

Will know to update the plugin right away if we experience something
similar in the future (btw I update all plugins weekly but don’t have auto
updates enabled on production since that can also break the site).

**Comment by gusaus** [comment]
Closing after realizing updating to the latest version (of Events Calendar) fixed the problem.
